# 第一章，NumPy函数库基础

ESC 后 H键显示快捷键帮助 

In [1]:
from numpy import *

In [7]:
random.rand(4,4)

array([[ 0.91808235,  0.45326496,  0.49422599,  0.07563621],
       [ 0.87447297,  0.97004278,  0.66127832,  0.07281192],
       [ 0.44189803,  0.14694069,  0.69307228,  0.59371926],
       [ 0.55265476,  0.88027111,  0.55147259,  0.7507883 ]])

构造一个4*4的随机数组

In [12]:
randMat = mat(random.rand(4,4))

In [13]:
randMat.I

matrix([[ 5.38589653, -7.73984338, -6.51945611,  7.96985654],
        [-6.21710312,  6.87550316,  6.98224948, -6.65952484],
        [ 1.48072145, -0.51667977, -2.37324069,  2.10097867],
        [ 0.91554217,  0.26547756,  0.90076228, -1.04037236]])

In [14]:
invRandMat = randMat.I

In [15]:
randMat*invRandMat

matrix([[  1.00000000e+00,   1.11022302e-16,   2.22044605e-16,
           0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [ -4.44089210e-16,   0.00000000e+00,   1.00000000e+00,
           8.88178420e-16],
        [  0.00000000e+00,   0.00000000e+00,  -8.88178420e-16,
           1.00000000e+00]])

结果应为单位矩阵，除了对角线元素为1，其余元素应该全为0。实际仍留了些很小的元素，这是计算机处理误差产生的结果。

In [17]:
myEye = randMat*invRandMat

In [18]:
myEye -eye(4)

matrix([[ -1.11022302e-16,   1.11022302e-16,   2.22044605e-16,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [ -4.44089210e-16,   0.00000000e+00,   0.00000000e+00,
           8.88178420e-16],
        [  0.00000000e+00,   0.00000000e+00,  -8.88178420e-16,
           0.00000000e+00]])

函数eye（4）创建4*4的单位矩阵，此为误差值。